export const FETCH_EVENT = 'FETCH_EVENT';
export const FETCH_ABOUT = 'FETCH_ABOUT';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const SEND_MESSAGE_LOADING = 'SEND_MESSAGE_LOADING';
export const USER_LOGIN = 'USER_LOGIN';